config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root to: "food#index"

  # Defines a route called "general_shopping_list" that will be available at "/general_shopping_list"
  get "general_shopping_list", to: "recipe#general_shopping_list"
  # Defines a route called "public_recipes" that will be available at "/public_recipes"
  get "public_recipes", to: "recipe#public_recipes"

  resources "recipe", :path => "recipes", only: [:index, :show, :new, :create, :update, :destroy] do
    resources "recipe_food", only: [:new, :create, :destroy]
  end
  resources "food", :path => "foods", only: [:index, :new, :create, :destroy]
  resources :users
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user (not logged in)

    if user.admin?
      can :manage, :all # admin can do anything
    else
      can :read, :all # guest user can read everything
      can :manage, Food, food_id: user.id # user can manage their own foods
      can :manage, Recipe, recipe_id: user.id # user can manage their own recipes

    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/food.rb
class Food < ApplicationRecord
  belongs_to :user
  has_many :recipe_foods, dependent: :destroy
  validates :name, presence: true, length: { maximum: 50 }, format: { with: /\A[a-zA-Z0-9]+\z/ }
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user
  has_many :recipe_foods, dependent: :destroy

  validates :name, presence: true, length: { maximum: 50 }, format: { with: /\A[a-zA-Z0-9]+\z/ }
end

app/models/recipe_food.rb
class RecipeFood < ApplicationRecord
  belongs_to :recipe, foreign_key: 'recipe_id'
  belongs_to :food, foreign_key: 'food_id'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :foods
  has_many :recipes

  validates :name, presence: true, length: { maximum: 50 }

  def admin?
    role == 'admin'
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # make a current_user method available to all controllers
  before_action :update_allowed_parameters, if: :devise_controller? # allow name and bio to be updated
  before_action :set_user

  protected

  def set_user
    ## to get the current user via session_id
    @current_user = User.find_by(id: session[:user_id]) if session[:user_id]
    ## to authenticate user via devise unless the current user have a session
    p @current_user
    authenticate_user! unless @current_user
  end

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) do |u|
      u.permit(:name, :email, :password, :password_confirmation)
    end
  end
end

app/controllers/food_controller.rb
class FoodController < ApplicationController
  def index
    @foods = Food.where(user_id: current_user.id)
  end

  def new
    @food = Food.new
  end

  def create
    @food = Food.new(food_params)
    @food.user_id = current_user.id

    if @food.save
      redirect_to root_path
    else
      render 'new'
    end
  end

  def destroy
    @food = Food.find(params[:id])

    if @food.destroy
      flash[:notice] = 'Food was successfully deleted.'
      redirect_to root_path
    else
      flash[:error] = 'There was an error deleting the food.'
      render :show, status: 400
    end
  end

  private

  def food_params
    params.require(:food).permit(:name, :price, :quantity, :measurement_unit)
  end
end

app/controllers/recipe_controller.rb
class RecipeController < ApplicationController
  def index
    # Get all the user's recipes
    @recipes = Recipe.where(user_id: current_user.id)
    @owner = current_user
  end

  def show
    # Get the recipe
    @recipe = Recipe.find(params[:id])
    @owner = current_user
  end

  def new
    # Create a new recipe
    @recipe = Recipe.new
  end

  def create
    # Create a new recipe
    @recipe = Recipe.new(recipe_params)
    @recipe.user_id = current_user.id

    # Save the recipe
    if @recipe.save
      redirect_to @recipe
    else
      redirect_to new_recipe_path
    end
  end

  def update
    # Get the recipe and toggle the public attribute
    @recipe = Recipe.find(params[:id])
    @recipe.public = !@recipe.public
    if @recipe.save
      flash[:notice] = 'Recipe was successfully updated.'
    else
      flash[:error] = 'There was an error updating the recipe.'
    end
    redirect_to recipe_path
  end

  def destroy
    # Get the recipe
    @recipe = Recipe.find(params[:id])
    if @recipe.destroy
      flash[:notice] = 'Recipe was successfully deleted.'
    else
      flash[:error] = 'There was an error deleting the recipe.'
    end
    redirect_to recipe_path
  end

  def general_shopping_list
    # Find all food recipes for the current user but the FoodRcipe does not have a user_id
    @foods = RecipeFood.where(recipe_id: Recipe.where(user_id: current_user.id).pluck(:id)).includes(:food)
    @total_price = 0
    @foods.each do |food|
      @total_price += food.food.price * food.quantity
    end
  end

  def public_recipes
    # Get all the public The public recipes or the recipes that the user created
    @recipes = Recipe.where('public = ? OR user_id = ?', true, current_user.id)
    @owner = current_user
  end

  private

  def recipe_params
    params.permit(:name, :description, :cooking_time, :preparation_time, :public)
  end
end

app/controllers/recipe_food_controller.rb
class RecipeFoodController < ApplicationController
  def new
    @recipe_food = RecipeFood.new
    @recipe = Recipe.find(params[:recipe_id])
    @foods = Food.where(user_id: current_user.id)
  end

  def create
    @recipe_food = RecipeFood.new(recipe_food_params)
    @recipe_food.food_id = params[:recipe_food][:food_id]
    @recipe_food.recipe_id = params[:recipe_id]

    p @recipe_food
    if @recipe_food.save
      redirect_to recipe_path(params[:recipe_id])
      flash[:notice] = 'Recipe food was successfully created.'
    else
      redirect_to new_recipe_recipe_food_path(params[:recipe_id])
      # reload the page

      respond_to do |format|
        format.js { render inline: 'location.reload();' }
      end

      flash[:error] = 'There was an error creating the recipe food.'
    end
  end

  def destroy
    @recipe_food = RecipeFood.find(params[:id])
    if @recipe_food.destroy
      flash[:notice] = 'Recipe food was successfully deleted.'
    else
      flash[:error] = 'There was an error deleting the recipe food.'
    end
    redirect_to recipe_path(params[:recipe_id])
  end

  private

  def recipe_food_params
    params.require(:recipe_food).permit(:food_id, :quantity)
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/food_helper.rb
module FoodHelper
end

app/helpers/recipe_food_helper.rb
module RecipeFoodHelper
end

app/helpers/recipe_helper.rb
module RecipeHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/food/index.html.erb
<section class="bg-gray-100 min-h-screen py-5 p-2">
  <div class="flex justify-end m-5">
    <%= link_to new_food_path() do %>
    <div
      class="inline-block rounded bg-indigo-600 px-4 py-2 text-xs font-medium text-white hover:bg-indigo-700"
    >
      Add food
    </div>
    <% end %>
  </div>

  <div class="p-4">
    <div class="form">
      <table class="min-w-full divide-y-2 divide-gray-500 text-sm bg-slate-50 rounded-lg">
        <thead>
          <tr id="form_list">
            <th class="whitespace-nowrap px-4 py-2 text-left font-medium text-gray-900">Food</th>
            <th class="whitespace-nowrap px-4 py-2 text-left font-medium text-gray-900">
              Measurement Unit
            </th>
            <th class="whitespace-nowrap px-4 py-2 text-left font-medium text-gray-900">
              Unit Price
            </th>
            <th class="whitespace-nowrap px-4 py-2 text-left font-medium text-gray-900">Actions</th>
          </tr>
        </thead>
        <tbody class="divide-y divide-gray-200">
          <% @foods.each do |food| %>
          <tr>
            <td class="whitespace-nowrap px-4 py-2 font-medium text-gray-900"><%= food.name %></td>
            <td class="whitespace-nowrap px-4 py-2 text-gray-700">
              <%= food.quantity %> <%= food.measurement_unit %>
            </td>
            <td class="whitespace-nowrap px-4 py-2 text-gray-700"><%= food.price %></td>
            <td>
              <%= link_to "Remove", food_path(id: food.id), data: { turbo_method: :delete },
              class:"inline-block rounded bg-indigo-600 px-4 py-2 text-xs font-medium text-white
              hover:bg-indigo-700" %>
            </td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</section>

app/views/food/new.html.erb
<div class="form-container border-black">
  <h1 class="h1">please add a new food &#8595;</h1>

  <%= render "shared/form", food: @food %>
<div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FoodRecipes</title>
    <meta name="viewport" content="width=device-width,initial-scale=1" />
    <%= csrf_meta_tags %> <%= csp_meta_tag %> <%= stylesheet_link_tag "application",
    "data-turbo-track": "reload" %> <%= javascript_importmap_tags %>
    <%= stylesheet_link_tag "tailwind", "inter-font",
    "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "food.css"%>
  </head>

  <body>
    <% if user_signed_in? %> <%= render "shared/nav" %> <% end %>
    <% if notice %> <p class="text-slate-500 bg-yellow-200/50 p-4"><%= notice %></p> <% end %>
    <% if alert %> <p class="text-slate-500 bg-red-200/50 p-4"><%= alert %></p> <% end %>
    <%= yield %>
  </body>
</html>

app/views/recipe/general_shopping_list.html.erb
<section class="bg-gray-100 min-h-screen">
  <div class="max-w-screen-xl py-4 sm:py-6 px-4 mx-auto sm:px-6 lg:px-8">
    <div class="flex flex-col gap-y-8 items-center lg:gap-x-16">
      <div class="mx-auto max-w-lg text-center lg:mx-0">
        <h2 class="text-3xl font-bold sm:text-4xl">Shopping List</h2>

        <div class="flex flex-col mt-6 gap-4">
          <h3 class="text-sm">Total price: <%= @total_price %> $</h3>
          <h3 class="text-sm">Amount of food items to buy: <%= @foods.length() %></h3>
        </div>
      </div>

      <% if @foods %>
      <div class="sm:pt-10 w-full sm:mt-12">
        <table class="min-w-full divide-y-2 divide-gray-500 text-sm bg-slate-50 rounded-lg">
          <thead>
            <tr>
              <th class="whitespace-nowrap px-4 py-2 text-left font-medium text-gray-900">Food</th>
              <th class="whitespace-nowrap px-4 py-2 text-left font-medium text-gray-900">
                Quantity
              </th>
              <th class="whitespace-nowrap px-4 py-2 text-left font-medium text-gray-900">Price</th>
            </tr>
          </thead>

          <tbody class="divide-y divide-gray-200">
            <% @foods.each do |recipe_food| %>
            <tr>
              <td class="whitespace-nowrap px-4 py-2 font-medium text-gray-900">
                <%= recipe_food.food.name %>
              </td>
              <td class="whitespace-nowrap px-4 py-2 text-gray-700">
                <%= recipe_food.food.quantity.to_i * recipe_food.quantity.to_i %> <%=
                recipe_food.food.measurement_unit %>
              </td>
              <td class="whitespace-nowrap px-4 py-2 text-gray-700">
                <%= recipe_food.food.price.to_i * recipe_food.quantity.to_i %> $
              </td>
            </tr>
            <% end %>
          </tbody>
        </table>
      </div>
      <% end %>
    </div>
  </div>
</section>

app/views/recipe/index.html.erb
<section class="bg-gray-100">
  <div class="mx-auto max-w-screen-2xl px-4 py-16 sm:px-6 lg:px-8">
    <div class="items-end justify-between sm:flex">
      <div class="max-w-xl">
        <h2 class="text-4xl font-bold tracking-tight sm:text-5xl">Read your favorite recipes</h2>

        <p class="mt-8 max-w-lg text-gray-500">
          These are the recipes that you have saved to your own cookbook. You can also add your own
          recipes to your cookbook.
        </p>
      </div>
    </div>

    <div class="mt-8 grid grid-cols-1 gap-4  lg:grid-cols-2">
      <% @recipes.each do |recipe| %> <%= render "shared/recipe_card", recipe: recipe %> <% end %>
    </div>
  </div>
</section>

app/views/recipe/new.html.erb
<section class="mx-auto max-w-screen-xl px-4 py-16 sm:px-6 lg:px-8 p-4 md:w-1/2">
  <div class="mx-auto max-w-lg text-center">
    <h1 class="text-2xl font-bold sm:text-3xl">New Recipe</h1>
  </div>

  <%= form_with url: '/recipes', method: :post, class:"mx-auto mt-8 mb-0 max-w-md space-y-4" do |f|
  %>
  <div>
    <%= f.label :name, class:"sr-only" %>

    <div class="relative">
      <%= f.text_field :name, class:"w-full rounded-lg border-gray-200 p-4 pr-12 text-sm shadow-sm",
      placeholder:"Recipe Name" %>
    </div>
  </div>

  <div>
    <%= f.label :description, class:"sr-only" %>

    <div class="relative">
      <%= f.text_area :description, class:"w-full rounded-lg border-gray-200 p-3 text-sm",
      placeholder:"Enter the text", rows:"8" %>
    </div>
  </div>

  <div>
    <%= f.label :cooking_time, class:"sr-only" %>

    <div class="relative">
      <%= f.number_field :cooking_time, class:"w-full rounded-lg border-gray-200 p-4 pr-12 text-sm",
      placeholder:"Cooking Time" %>
    </div>
  </div>

  <div>
    <%= f.label :preparation_time, class:"sr-only" %>

    <div class="relative">
      <%= f.number_field :preparation_time, class:"w-full rounded-lg border-gray-200 p-4 pr-12
      text-sm", placeholder:"Preparation_time" %>
    </div>
  </div>

  <div class="flex justify-end">
    <%= f.label :public, class:"sr-only" %>
    <div class="relative flex gap-4">
      <div>public :</div>
      <%= f.check_box :public, class:" rounded-lg w-6 h-6 border-gray-200 ", value: false %>
    </div>
  </div>

  <div class="flex items-center justify-center">
    <%= f.submit "SUBMIT", class:"inline-block rounded-lg bg-blue-500 px-5 py-3 text-sm font-medium
    text-white" %>
  </div>
  <% end %>
</section>

app/views/recipe/public_recipes.html.erb
<section class="bg-gray-100">
  <div class="mx-auto max-w-screen-2xl px-4 py-16 sm:px-6 lg:px-8">
    <div class="items-end justify-between sm:flex">
      <div class="max-w-xl">
        <h2 class="text-4xl font-bold tracking-tight sm:text-5xl">Public Recipes</h2>

        <p class="mt-8 max-w-lg text-gray-500">
          These are the recipes that are public. You can view them and add them to your shopping list.
        </p>
      </div>
    </div>

    <div class="mt-8 grid grid-cols-1 gap-4  lg:grid-cols-2">
      <% @recipes.each do |recipe| %> <%= render "shared/recipe_card", recipe: recipe %> <% end %>
    </div>
  </div>
</section>

app/views/recipe/show.html.erb
<section class="bg-gray-100 min-h-screen">
  <div class="max-w-screen-xl px-4 py-8 sm:py-12 sm:px-6 lg:py-16 lg:px-8">
    <div class="grid grid-cols-1 gap-y-8 lg:grid-cols-2 lg:items-center lg:gap-x-16">
      <div class="mx-auto max-w-lg text-center lg:mx-0 lg:text-left">
        <div class="flex justify-between">
          <h2 class="text-3xl font-bold sm:text-4xl"><%= @recipe.name %></h2>

          <% if @recipe.user_id == @owner.id %>
          <h3 class="mt-2 mr-8">
            Public: 
            <%= link_to recipe_path(@recipe), data: { turbo_method: "PUT"} do %>
            <span class="ml-4"> <%= render "shared/public", recipe: @recipe %></span>
            <% end %>
          </h3>
          <% end %>
        </div>

        <p class="mt-4 text-gray-600"><%= @recipe.description %></p>

        <h3 class="text-sm mt-6">Preparation time: <%= @recipe.preparation_time / 60 %> minutes</h3>

        <h3 class="text-sm">Cooking time: <%= @recipe.cooking_time / 60 %> minutes</h3>

        <div class="flex justify-between gap-4">
          <%= link_to general_shopping_list_path  do %>
          <div
            class="mt-8 inline-block rounded bg-indigo-600 p-2 text-sm font-medium text-white transition hover:bg-indigo-700 focus:outline-none focus:ring focus:ring-yellow-400"
          >
            Generate shopping list
          </div>
          <% end %>

          <a
            href = <%= new_recipe_recipe_food_path(@recipe) %>
            data-turbo= "false"
            class="mt-8 inline-block rounded bg-indigo-600 p-2 text-sm font-medium text-white transition hover:bg-indigo-700 focus:outline-none focus:ring focus:ring-yellow-400"
          >
            Add ingredients
        </a>
        </div>
      </div>

      <% if @recipe.recipe_foods %>
      <div class="">
        <table class="min-w-full divide-y-2 divide-gray-500 text-sm bg-slate-50 rounded-lg">
          <thead>
            <tr>
              <th class="whitespace-nowrap px-4 py-2 text-left font-medium text-gray-900">Food</th>
              <th class="whitespace-nowrap px-4 py-2 text-left font-medium text-gray-900">
                Quantity
              </th>
              <th class="whitespace-nowrap px-4 py-2 text-left font-medium text-gray-900">Price</th>
              <th class="whitespace-nowrap px-4 py-2 text-left font-medium text-gray-900">
                Actions
              </th>
            </tr>
          </thead>

          <tbody class="divide-y divide-gray-200">
            <% @recipe.recipe_foods.each do |recipe_food| %>
            <tr>
              <td class="whitespace-nowrap px-4 py-2 font-medium text-gray-900">
                <%= recipe_food.food.name %>
              </td>
              <td class="whitespace-nowrap px-4 py-2 text-gray-700">
                <%= recipe_food.food.quantity.to_i * recipe_food.quantity.to_i %> <%=
                recipe_food.food.measurement_unit %>
              </td>
              <td class="whitespace-nowrap px-4 py-2 text-gray-700">
                <%= recipe_food.food.price.to_i * recipe_food.quantity.to_i %> $
              </td>
              <td class="whitespace-nowrap px-4 py-2">
                <%= link_to "Remove",
                recipe_recipe_food_path(recipe_id:@recipe.id,id:recipe_food.id), data: {
                turbo_method: :delete }, class:"inline-block rounded bg-indigo-600 px-4 py-2 text-xs
                font-medium text-white hover:bg-indigo-700" %>
              </td>
            </tr>
            <% end %>
          </tbody>
        </table>
      </div>
      <% end %>
    </div>
  </div>
</section>

app/views/recipe_food/index.html.erb
<!-- The list of foods -->
<section class="bg-gray-100 min-h-screen">
  <div class="flex flex-col items-center">
    <div class="items-end justify-between sm:flex">
      <div class="max-w-xl">
        <h2 class="text-4xl font-bold tracking-tight sm:text-5xl">All your Foods</h2>

        <p class="mt-8 max-w-lg text-gray-500">
          These are the Food items you have in your pantry. You can add them to your recipes.
        </p>
      </div>
    </div>

    <div class="mt-10 flex p-5 w-full">
      <table class="min-w-full divide-y-2 divide-gray-500 text-sm bg-slate-50 rounded-lg">
        <thead>
          <tr>
            <th class="whitespace-nowrap px-4 py-2 text-left font-medium text-gray-900">Food</th>
            <th class="whitespace-nowrap px-4 py-2 text-left font-medium text-gray-900">
              Quantity
            </th>
            <th class="whitespace-nowrap px-4 py-2 text-left font-medium text-gray-900">Actions</th>
          </tr>
        </thead>
        <tbody class="divide-y divide-gray-200">
          <% @foods.each do |food| %> <%= form_with model:@recipe_food ,url: recipe_recipe_food_index_path(@recipe.id) ,
          method: :post do |f| %>
          <tr>
            <td class="whitespace-nowrap px-4 py-2 font-medium text-gray-900"><%= food.name %></td>
            <td class="whitespace-nowrap px-4 py-2 text-gray-700">
              <%= f.hidden_field :food_id, value: food.id %>
              <%= f.number_field :quantity %>
            </td>
            <td class="whitespace-nowrap px-4 py-2">
              <%= f.submit "Add", class: "inline-block rounded bg-indigo-600 px-4 py-2 text-xs
              font-medium text-white hover:bg-indigo-700" %>
            </td>
          </tr>
          <% end %> <% end %>
        </tbody>
      </table>
    </div>
  </div>
</section>

app/views/recipe_food/new.html.erb
<!-- The list of foods -->
<section class="bg-gray-100 min-h-screen">
  <div class="flex flex-col items-center">
    <div class="items-end justify-between sm:flex">
      <div class="max-w-xl">
        <h2 class="text-4xl font-bold tracking-tight sm:text-5xl">All your Foods</h2>

        <p class="mt-8 max-w-lg text-gray-500">
          These are the Food items you have in your pantry. You can add them to your recipes.
        </p>
      </div>
    </div>

    <div class="mt-10 flex p-5 w-full">
      <table class="min-w-full divide-y-2 divide-gray-500 text-sm bg-slate-50 rounded-lg">
        <thead>
          <tr>
            <th class="whitespace-nowrap px-4 py-2 text-left font-medium text-gray-900">Food</th>
            <th class="whitespace-nowrap px-4 py-2 text-left font-medium text-gray-900">
              Quantity
            </th>
            <th class="whitespace-nowrap px-4 py-2 text-left font-medium text-gray-900">Actions</th>
          </tr>
        </thead>
        <tbody class="divide-y divide-gray-200">
          <% @foods.each do |food| %>
          <tr>
            <%= form_with model:@recipe_food ,url: recipe_recipe_food_index_path(@recipe.id) ,
            method: :post do |f| %>
            <td class="whitespace-nowrap px-4 py-2 font-medium text-gray-900"><%= food.name %></td>
            <td class="whitespace-nowrap px-4 py-2 text-gray-700">
              <%= f.hidden_field :food_id, value: food.id %> <%= f.number_field :quantity %>
            </td>
            <td class="whitespace-nowrap px-4 py-2">
              <%= f.submit "Add", class: "inline-block rounded bg-indigo-600 px-4 py-2 text-xs
              font-medium text-white hover:bg-indigo-700" %>
            </td>
            <% end %>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</section>

app/views/shared/_form.html.erb
<%= form_with model: @food, url:"/foods", method: :post do |form| %>
    <div class="form-group">
        <%= form.label :name %>
        <%= form.text_field :name %>
    </div>

    <div class="form-group">
        <%= form.label :quantity %>
        <%= form.number_field :quantity %>
    </div>

    <div class="form-group">
        <%= form.label :measurement_unit %>
        <%= form.text_field :measurement_unit %>
    </div>

    <div class="form-group">
        <%= form.label :price %>
        <%= form.number_field :price %>
    </div>
    <div class="form-group">
      <%= form.submit "Create food", class: "submit-form" %>
       <button class="back"><%=link_to 'Back to foods', root_path %></button>
    </div>
<% end %>

app/views/shared/_nav.html.erb
<header aria-label="Site Header" class="bg-white">
  <div class="mx-auto max-w-screen-xl px-4 sm:px-6 lg:px-8">
    <div class="flex h-16 items-center justify-center">
      <div class="md:flex md:items-center md:gap-12">
        <nav aria-label="Site Nav" class="">
          <ul class="flex items-center gap-6 text-sm justify-between">
            <li>
              <%= link_to "Foods", food_index_path, class: "text-gray-500 transition
              hover:text-gray-500/75" %>
            </li>

            <li>
              <%= link_to "Recipes", recipe_index_path, class: "text-gray-500 transition
              hover:text-gray-500/75" %>
            </li>

            <li>
              <%= link_to "Shopping List", general_shopping_list_path, class: "text-gray-500 transition
              hover:text-gray-500/75" %>
            </li>

            <li>
              <%= link_to "Public Recipes", public_recipes_path, class: "text-gray-500 transition
              hover:text-gray-500/75" %>
            </li>

            <li>
              <%= link_to "Create New Recipe", new_recipe_path, class: "text-gray-50 transition bg-violet-500 hover:bg-violet-700 hover:text-white px-4 py-2 rounded-md text-sm 
              hover:text-gray-500/75" %>
            </li>
          </ul>
        </nav>
      </div>
    </div>
  </div>
</header>

app/views/shared/_public.html.erb
<label for="AcceptConditions" class="relative h-4 w-7 cursor-pointer">
  <% if @recipe.public %>
  <input
    type="checkbox"
    id="AcceptConditions"
    checked
    class="peer sr-only [&:checked_+_span_svg[data-unchecked-icon]]:hidden [&:checked_+_span_svg[data-checked-icon]]:block"
  />
  <% else %>
  <input
    type="checkbox"
    id="AcceptConditions"
    class="peer sr-only [&:checked_+_span_svg[data-unchecked-icon]]:hidden [&:checked_+_span_svg[data-checked-icon]]:block"
  />
  <% end %>

  <span
    class="absolute inset-0 z-10 m-1 inline-flex h-3 w-3 items-center justify-center rounded-full bg-white text-gray-400 transition peer-checked:translate-x-3 peer-checked:text-green-600"
  >
    <svg
      data-unchecked-icon
      xmlns="http://www.w3.org/2000/svg"
      class="h-3 w-3"
      viewBox="0 0 20 20"
      fill="currentColor"
    >
      <path
        fill-rule="evenodd"
        d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z"
        clip-rule="evenodd"
      />
    </svg>

    <svg
      data-checked-icon
      xmlns="http://www.w3.org/2000/svg"
      class="hidden h-3 w-3"
      viewBox="0 0 20 20"
      fill="currentColor"
    >
      <path
        fill-rule="evenodd"
        d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z"
        clip-rule="evenodd"
      />
    </svg>
  </span>

  <span
    class="absolute inset-0 rounded-full bg-gray-300 transition peer-checked:bg-green-500 w-8 h-5"
  ></span>
</label>

app/views/shared/_recipe_card.html.erb
<blockquote class="flex h-full flex-col justify-between bg-white p-10 hover:shadow-lg">
  <%= link_to recipe_path(recipe) do %>
  <div>
    <div class="mt-4">
      <h3 class="text-xl font-bold text-pink-600 sm:text-2xl"><%= recipe.name %></h3>

      <p class="mt-4 text-gray-600"><%= recipe.description.truncate(150) %></p>
    </div>
  </div>
  <% end %>
  <div class="flex h-10">
    <% if @owner.id == recipe.user_id %>

    <footer class=" mt-2 flex-1 text-gray-500 hover:text-red-500 cursor-pointer flex justify-end">
      <%= link_to "Delete Recipe", recipe_path(id: recipe.id), data: { turbo_method: :delete },
      class:"block rounded bg-indigo-600 px-4 py-2 text-xs font-medium text-white h-fit-content
      hover:bg-indigo-700" %>
    </footer>

    <% end %>
  </div>
</blockquote>